apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-config
#  namespace: personas se indica segun entorno
data:
  SPRING_CLOUD_CONFIG_URI: "http://ms-config-svc.articulos-dev.svc.cluster.local"
  NAME_SPACE: "articulos-dev"
  MS_AUTH: "http://ms-auth-svc.seguridad-dev.svc.cluster.local"
  BUENDIA: "http://ms-articulo-compose-svc.buendia-dev.svc.cluster.local"
  BODEGA: "http://ms-articulo-compose-svc.bodega-dev.svc.cluster.local"
  FERRETERIA: "http://ms-articulo-compose-svc.ferreteria-dev.svc.cluster.local"
  INSUMOS: "http://ms-articulo-compose-svc.insumos-dev.svc.cluster.local"
  SANCARLOS: "http://ms-articulo-compose-svc.sancarlos-dev.svc.cluster.local"
  RIOCONEJO: "http://ms-articulo-compose-svc.rioconejo-dev.svc.cluster.local"
  SANPABLO: "http://ms-articulo-compose-svc.sanpablo-dev.svc.cluster.local"
  SPRING_PROFILES_ACTIVE: "kubernetes"

