apiVersion: v1
kind: Service
metadata:
  name: ms-articulo-compose-svc
spec:
  type: ClusterIP
  selector:
    app: ms-articulo-compose
  ports:
    - protocol: TCP
      name: main
      port: 80
      targetPort: 80
