#version: "3.9"
services:
  ms-articulos:
    image: ${REGISTRY}/ms-articulos:${MS_ARTICULOS_VERSION}
    container_name: ms-articulos
    build:
      context: ./
      dockerfile: /ms-articulos/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${PROFILE}
#networks:
#  spring-cloud-network:
#      driver: bridge
