apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-config
#  namespace: personas se indica segun entorno
data:
  SPRING_CLOUD_CONFIG_URI: "http://ms-config-svc.articulos-dev.svc.cluster.local"
  NAME_SPACE: "inventario-dev"
  MS_AUTH: "http://ms-auth-svc.seguridad-dev.svc.cluster.local"
  SPRING_PROFILES_ACTIVE: "kubernetes"

